### PR TITLE
Clean up and bump cdk-pgstac to latest eoapi-cdk

### PR DESCRIPTION
**Pull request by emileten**
- removed `.env` and `deploy.sh`, which were deployment tools living in the root of the repository that are not used anymore since we have a functional deployment github action. 
 - updated README, which was still describing a manual deployment. It's now describing the github action deployment.
 - bumped `cdk-pgstac` to `eoapi-cdk` 5.0.0 ([the name of the library was changed](https://github.com/developmentseed/eoapi-cdk/releases/tag/v5.0.0))

### CODE REVIEW

**Comment by emileten** [comment]
@jjfrench could you quickly check this and approve so that I can merge ? It's pretty minor, the cdk-pgstac bump is 4.2.2 -> 5.0.0, and the two changes with this bump are (1) the name changed to eoapi-cdk, (2) I improved one of the cloud formation outputs.

**Comment by jjfrench** [comment]
Do we want to import from eoapi-cdk as well?

**Comment by emileten** [comment]
Thanks @jjfrench. Anything else ?

**Comment by emileten** [comment]
hm I am not changing the package-lock file and that's what is used I think when dependencies are installed in the workflow...

**Comment by jjfrench** [comment]
Looks good, do we want to merge and then create another PR for the titiler fix?

**Comment by emileten** [comment]
I'd say : 
- let's move the bump to https://github.com/MAAP-Project/maap-eoapi/pull/15 since it depends on yet another update to eoapi-cdk
- let's keep here only the README change and deploy.sh removal and merge rn

**Pull request merged**
