### PR TITLE
Update eoapi-cdk with custom titiler-pgstac runtime

### PR DESCRIPTION
**Pull request by hrodmn**
### Tasks
- [x] Upgrade to `eoapi-cdk==7.2.1`
- [x] Override default runtime with custom runtime
- [x] Add `/cog` endpoints to custom runtime
- [x] Redirect `/mosaic` requests to `/searches`
- [ ] ~~Add special features from [impact-tiler](https://github.com/NASA-IMPACT/impact-tiler)~~
  - [ ] ~~MosaicJSON~~

I just copied the runtime files from [eoapi-cdk](https://github.com/developmentseed/eoapi-cdk/tree/main/lib/titiler-pgstac-api/runtime) then added the custom endpoint logic.

Rather than adding the `/stac` endpoints to this deployment for stac-ipyleaflet, we should do this: https://github.com/MAAP-Project/stac_ipyleaflet/issues/131. The `/stac` endpoints are all redundant with the `/collections/{collection_id}/items/{item}` endpoints (as long as the STAC items are in the database attached to titiler-pgstac instance).

The MosaicJSON endpoints are used heavily in `titiler.maap-project.org` so before adding the complicated runtime here I want to spend some time considering our options.

### CODE REVIEW

**Comment by hrodmn** [comment]
We are running Postgres 14 on our DB, this might be a good opportunity to upgrade to a more recent version (the latest is 16.3). I upgraded from 14 to 16 once at my last job and it went fine!

**Comment by jjfrench** [comment]
Changes look good, can use the test stack to deploy

**Comment by hrodmn** [comment]
The tests action is passing on the `test` deployment: https://github.com/MAAP-Project/maap-eoapi/actions/runs/10688960694/job/29633124387

I verified that the `/cog` endpoints are working with this [NOAA HRRR asset](https://titiler-pgstac.dit.maap-project.org/cog/WebMercatorQuad/map?url=vrt://https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrrr.20240808/conus/hrrr.t20z.wrfsfcf01.grib2?bands=1&bidx=1&maxzoom=9&colormap=[[[5,%2010],%20[0,%20236,%20236,%20255]],%20[[10,%2015],%20[1,%20160,%20246,%20255]],%20[[15,%2020],%20[0,%200,%20246,%20255]],%20[[20,%2025],%20[0,%20255,%200,%20255]],%20[[25,%2030],%20[0,%20200,%200,%20255]],%20[[30,%2035],%20[0,%20144,%200,%20255]],%20[[35,%2040],%20[255,%20255,%200,%20255]],%20[[40,%2045],%20[231,%20192,%200,%20255]],%20[[45,%2050],%20[255,%20144,%200,%20255]],%20[[50,%2055],%20[255,%200,%200,%20255]],%20[[55,%2060],%20[214,%200,%200,%20255]],%20[[60,%2065],%20[192,%200,%200,%20255]],%20[[65,%2070],%20[255,%200,%20255,%20255]],%20[[70,%2075],%20[153,%2085,%20201,%20255]]])

From what I can tell, we are not using the titiler-pgstac deployment anywhere in the `maap-documentation` repo so these changes are probably safe to merge! @jjfrench once you approve this PR I can merge it and deploy the new stack to `dev`.

**Review by jjfrench — APPROVED** [review]
🚀

**Pull request merged**
