### PR TITLE
Test badging on workflow

### PR DESCRIPTION
**Pull request by omshinde**
Initial step for adding badge for successful execution of the `tests` workflow - https://github.com/MAAP-Project/maap-eoapi/tree/test_badging_on_workflow#readme

### CODE REVIEW

**Review by jjfrench — APPROVED** [review]
This should work for the default (main) branch badge status if you want to fix the test back to test_collection.json - I believe you check the specific branches by adding `?branch=test_badging_on_workflow`

**Comment by omshinde** [comment]
Thanks @jjfrench ..I was checking if the badge shows failings status of the tests or not.. It does.. So, I will go ahead and merge this PR to check it on the `main` branch.

**Comment by jjfrench** [comment]
Need to "fix the test back to test_collection.json"

**Comment by omshinde** [comment]
Yes, I know. That was intentional to check if the badge gets updated on failing test or not. Pushing the correct tests again. :)

**Comment by jjfrench** [comment]
I thought you checked on this specific branch with the latest commit? You can view the badge on the specific branch's README

**Pull request merged**
